-- Première base Supabase issue de db.txt. À appliquer à un projet dédié et vide.
-- Aucun compte, mot de passe ou panier SQLite n'est importé.
begin;
create table public.segments_clients (
  id bigint generated by default as identity primary key,
  nom text not null unique, description text
);
create table public.clients (
  id uuid primary key references auth.users(id) on delete cascade,
  nom_complet text not null default '' check (length(nom_complet) <= 120),
  telephone text, adresse text,
  segment_id bigint references public.segments_clients(id),
  date_creation timestamptz not null default now()
);
create table public.categories (
  id bigint generated by default as identity primary key,
  nom text not null, parent_id bigint references public.categories(id),
  check (parent_id is distinct from id)
);
create table public.fournisseurs (
  id bigint generated by default as identity primary key,
  nom text not null unique, site_web text check (site_web is null or site_web ~ '^https://')
);
create table public.produits (
  id bigint generated by default as identity primary key,
  ref_fabricant text not null check (length(ref_fabricant) between 1 and 100),
  code_ean text check (code_ean is null or code_ean ~ '^[0-9]{8,14}$'),
  nom text not null, marque text not null default '',
  categorie_id bigint references public.categories(id),
  description text, specificite text, emballage_condition text,
  image_url text check (image_url is null or image_url ~ '^https://'),
  pdf_url text check (pdf_url is null or pdf_url ~ '^https://'),
  date_creation timestamptz not null default now(),
  unique (marque, ref_fabricant)
);
create table public.produits_fournisseurs (
  id bigint generated by default as identity primary key,
  produit_id bigint not null references public.produits(id) on delete restrict,
  fournisseur_id bigint not null references public.fournisseurs(id) on delete restrict,
  ref_fournisseur text,
  prix numeric(12,2) check (prix >= 0),
  devise text not null default 'EUR' check (devise = 'EUR'),
  nature_prix text not null default 'demonstration' check (nature_prix in ('demonstration','public','negocie')),
  conditionnement text,
  url_produit text check (url_produit is null or url_produit ~ '^https://'),
  date_verification timestamptz,
  date_creation timestamptz not null default now(),
  unique(produit_id, fournisseur_id)
);
create table public.paniers (
  id bigint generated by default as identity primary key,
  client_id uuid not null unique references public.clients(id) on delete cascade,
  date_creation timestamptz not null default now()
);
create table public.articles_panier (
  id bigint generated by default as identity primary key,
  panier_id bigint not null references public.paniers(id) on delete cascade,
  offre_id bigint not null references public.produits_fournisseurs(id) on delete restrict,
  quantite integer not null default 1 check (quantite between 1 and 9999),
  unique(panier_id, offre_id)
);
create table public.besoins_clients (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients(id) on delete cascade,
  categorie_id bigint references public.categories(id),
  marque text, produit text not null,
  quantite_annuelle integer check (quantite_annuelle >= 0),
  unite text, budget_estime numeric(12,2) check (budget_estime >= 0),
  date_saisie timestamptz not null default now()
);
create index on public.clients(segment_id);
create index on public.categories(parent_id);
create index on public.produits(categorie_id);
create index on public.produits(nom,id);
create index on public.produits_fournisseurs(fournisseur_id);
create index on public.articles_panier(offre_id);
create index on public.besoins_clients(client_id);
create index on public.besoins_clients(categorie_id);

-- Droits explicites : les grants de la plateforme peuvent varier.
revoke all on table public.segments_clients, public.clients, public.categories, public.fournisseurs,
 public.produits, public.produits_fournisseurs, public.paniers, public.articles_panier, public.besoins_clients
 from anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select on public.segments_clients, public.categories, public.fournisseurs, public.produits, public.produits_fournisseurs to anon, authenticated;
grant select, insert, update on public.clients to authenticated;
grant select, insert on public.paniers to authenticated;
grant select, insert, update, delete on public.articles_panier, public.besoins_clients to authenticated;
grant insert, update, delete on public.segments_clients, public.categories, public.fournisseurs, public.produits, public.produits_fournisseurs to authenticated;
grant usage, select on sequence public.segments_clients_id_seq, public.categories_id_seq,
 public.fournisseurs_id_seq, public.produits_id_seq, public.produits_fournisseurs_id_seq,
 public.paniers_id_seq, public.articles_panier_id_seq, public.besoins_clients_id_seq to authenticated;

alter table public.segments_clients enable row level security;
alter table public.clients enable row level security;
alter table public.categories enable row level security;
alter table public.fournisseurs enable row level security;
alter table public.produits enable row level security;
alter table public.produits_fournisseurs enable row level security;
alter table public.paniers enable row level security;
alter table public.articles_panier enable row level security;
alter table public.besoins_clients enable row level security;

create policy segments_lecture on public.segments_clients for select to anon, authenticated using(true);
create policy categories_lecture on public.categories for select to anon, authenticated using(true);
create policy fournisseurs_lecture on public.fournisseurs for select to anon, authenticated using(true);
create policy produits_lecture on public.produits for select to anon, authenticated using(true);
-- Les tarifs sont invisibles pour anon, y compris via RPC et requêtes imbriquées.
create policy offres_lecture on public.produits_fournisseurs for select to authenticated
 using ((select auth.uid()) is not null and coalesce((select auth.jwt())->>'is_anonymous','false') <> 'true');
-- Le rôle provient uniquement des app_metadata définies par un administrateur.
create policy segments_admin on public.segments_clients for all to authenticated
 using ((select auth.jwt())->'app_metadata'->>'role' = 'admin') with check ((select auth.jwt())->'app_metadata'->>'role' = 'admin');
create policy categories_admin on public.categories for all to authenticated
 using ((select auth.jwt())->'app_metadata'->>'role' = 'admin') with check ((select auth.jwt())->'app_metadata'->>'role' = 'admin');
create policy fournisseurs_admin on public.fournisseurs for all to authenticated
 using ((select auth.jwt())->'app_metadata'->>'role' = 'admin') with check ((select auth.jwt())->'app_metadata'->>'role' = 'admin');
create policy produits_admin on public.produits for all to authenticated
 using ((select auth.jwt())->'app_metadata'->>'role' = 'admin') with check ((select auth.jwt())->'app_metadata'->>'role' = 'admin');
create policy offres_admin on public.produits_fournisseurs for all to authenticated
 using ((select auth.jwt())->'app_metadata'->>'role' = 'admin') with check ((select auth.jwt())->'app_metadata'->>'role' = 'admin');
create policy profil_lecture on public.clients for select to authenticated using ((select auth.uid()) = id);
create policy profil_creation on public.clients for insert to authenticated with check ((select auth.uid()) = id);
create policy profil_modification on public.clients for update to authenticated
 using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy panier_lecture on public.paniers for select to authenticated using ((select auth.uid()) = client_id);
create policy panier_creation on public.paniers for insert to authenticated with check ((select auth.uid()) = client_id);
create policy articles_proprietaire on public.articles_panier for all to authenticated
 using (exists(select 1 from public.paniers p where p.id=panier_id and p.client_id=(select auth.uid())))
 with check (exists(select 1 from public.paniers p where p.id=panier_id and p.client_id=(select auth.uid())));
create policy besoins_proprietaire on public.besoins_clients for all to authenticated
 using ((select auth.uid()) = client_id) with check ((select auth.uid()) = client_id);

-- Recherche littérale, paginée : aucun regex issu d'une saisie utilisateur.
create function public.rechercher_catalogue(terme text default '', page_num integer default 0)
returns table(id bigint, ref_fabricant text, nom text, marque text, image_url text, offres jsonb)
language sql stable security invoker set search_path = '' as $$
 select p.id, p.ref_fabricant, p.nom, p.marque, p.image_url,
 coalesce((select jsonb_agg(jsonb_build_object(
   'id',pf.id,'fournisseur',f.nom,'prix',pf.prix,'nature_prix',pf.nature_prix,
   'conditionnement',pf.conditionnement,'date_verification',pf.date_verification,
   'url_produit',pf.url_produit) order by f.nom)
   from public.produits_fournisseurs pf join public.fournisseurs f on f.id=pf.fournisseur_id
   where pf.produit_id=p.id), '[]'::jsonb)
 from public.produits p
 where position(lower(left(coalesce(terme,''),100)) in lower(p.nom || ' ' || p.ref_fabricant || ' ' || p.marque)) > 0
 order by p.nom,p.id limit 24 offset (greatest(0,least(coalesce(page_num,0),100000)) * 24);
$$;
revoke all on function public.rechercher_catalogue(text,integer) from public;
grant execute on function public.rechercher_catalogue(text,integer) to anon, authenticated;

-- Ajout atomique, exécuté avec les droits et les règles RLS de l'appelant.
create function public.ajouter_au_panier(offre_id bigint, qte integer default 1)
returns bigint language plpgsql security invoker set search_path = '' as $$
declare owner_id uuid := auth.uid(); cart_id bigint; item_id bigint;
begin
 if owner_id is null then raise exception 'Connexion requise' using errcode='42501'; end if;
 if qte is null or qte < 1 or qte > 9999 then raise exception 'Quantité invalide' using errcode='22023'; end if;
 if not exists(select 1 from public.produits_fournisseurs pf where pf.id=offre_id) then
  raise exception 'Offre indisponible' using errcode='22023';
 end if;
 insert into public.paniers(client_id) values(owner_id) on conflict(client_id) do nothing;
 select p.id into cart_id from public.paniers p where p.client_id=owner_id;
 insert into public.articles_panier(panier_id,offre_id,quantite) values(cart_id,offre_id,qte)
 on conflict on constraint articles_panier_panier_id_offre_id_key do update
 set quantite=public.articles_panier.quantite + excluded.quantite
 returning id into item_id;
 return item_id;
end; $$;
revoke all on function public.ajouter_au_panier(bigint,integer) from public;
grant execute on function public.ajouter_au_panier(bigint,integer) to authenticated;
commit;
